version: '2.1'

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    networks:
    - web
    env_file:
    - .env
    links:
      - orbis_db:db
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:orbis.zone;PathPrefix:/api"
    - "traefik.port=3030"
    - "traefik.protocol=http"
    restart: always
    depends_on:
      orbis_db:
        condition: service_healthy
  client:
    build:
      context: client/
      dockerfile: Dockerfile
    networks:
    - web
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:orbis.zone;PathPrefix:/"
    - "traefik.port=80"
    - "traefik.protocol=http"
    restart: always
    links:
      - server

  imageproxy:
    image: willnorris/imageproxy
    command: -cache memory:200:4h -cache /tmp/imageproxy -addr 0.0.0.0:8080
    volumes:
      - ./data/imageproxy:/tmp/imageproxy
    networks:
    - web
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:orbis.zone;PathPrefixStrip:/imgproxy/"
    - "traefik.port=8080"
    - "traefik.protocol=http"
    restart: always
  orbis_db:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - web
    volumes:
      - orbis_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: orbis


networks:
  web:
    external: true

volumes:
  orbis_data:
