version: '2.1'

services:
  server:
    image: edcd/orbis-server
    build:
      context: server/
      dockerfile: Dockerfile
    networks:
    - web
    env_file:
    - .env
    links:
      - orbis_db:db
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:orbis.zone;PathPrefix:/api"
    - "traefik.port=3030"
    - "traefik.protocol=http"
    restart: always
    depends_on:
      orbis_db:
        condition: service_healthy
  client:
    image: edcd/orbis-client
    build:
      context: client/
      dockerfile: Dockerfile
    networks:
    - web
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:orbis.zone;PathPrefix:/"
    - "traefik.port=80"
    - "traefik.protocol=http"
    restart: always
    links:
      - server

  imaginary:
    image: h2non/imaginary:latest
    volumes:
      - images:/mnt/data
    networks:
      - web
    environment:
       PORT: 9000
    restart: always
    command: -enable-url-source -mount /mnt/data -concurrency 20 -http-cache-ttl 31556926 -enable-placeholder
    labels:
    - "traefik.docker.network=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:orbis.zone;PathPrefixStrip:/imgproxy/"
    - "traefik.port=9000"
    - "traefik.protocol=http"
  orbis_db:
    image: bitnami/postgresql:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - web
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - orbis_data:/bitnami
    restart: always
    environment:
      POSTGRESQL_PASSWORD: ${PG_PASSWORD}
      POSTGRESQL_USERNAME: orbis
      POSTGRESQL_DATABASE: orbis


networks:
  web:
    external: true

volumes:
  orbis_data:
  images:
