version: '3.1'

services:
  app:
    build: .
    networks:
    - orbis
    labels:
    - "traefik.docker.network=orbis_orbis"
    - "traefik.enable=true"
    - "traefik.basic.frontend.rule=Host:orbistest.willb.info"
    - "traefik.basic.port=3000"
    - "traefik.basic.protocol=http"
    restart: always
    command: sh -c './wait-for db:3306 -- node server.js'
    depends_on:
    - db
  db:
    image: bitnami/mariadb:latest
    networks:
    - orbis
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: orbis


networks:
  orbis:

volumes:
  orbis_data:
