export const HOME_GET_BUILDS_BEGIN = 'HOME_GET_BUILDS_BEGIN';
export const HOME_GET_BUILDS_SUCCESS = 'HOME_GET_BUILDS_SUCCESS';
export const HOME_GET_BUILDS_FAILURE = 'HOME_GET_BUILDS_FAILURE';
export const HOME_GET_BUILDS_DISMISS_ERROR = 'HOME_GET_BUILDS_DISMISS_ERROR';
