export const PROFILE_GET_PROFILE_BEGIN = 'PROFILE_GET_PROFILE_BEGIN';
export const PROFILE_GET_PROFILE_SUCCESS = 'PROFILE_GET_PROFILE_SUCCESS';
export const PROFILE_GET_PROFILE_FAILURE = 'PROFILE_GET_PROFILE_FAILURE';
export const PROFILE_GET_PROFILE_DISMISS_ERROR = 'PROFILE_GET_PROFILE_DISMISS_ERROR';
